name: Unit Test

# on:
#   pull_request:
#     branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test
